{{- if .Values.share }}
{{- range .Values.share }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "samba.name" $ }}-{{ .name }}
  namespace: {{ include "samba.namespace" . }}
spec:
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName -}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}