name: samba

services:
  samba:
    image: crazymax/samba
    container_name: samba
    network_mode: host
    volumes:
      - "./data:/data"
      - "./public:/samba/public"
      - "./share:/samba/share"
      - "./foo:/samba/foo"
      - "./foo-baz:/samba/foo-baz"
    environment:
      - "TZ=Europe/Paris"
      - "SAMBA_LOG_LEVEL=0"
    restart: always
